### ISSUE TITLE
Should the new handbook have a "Fundraising" section? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#102]
This is the Fundraising section in the current handbook: 
https://docs.carpentries.org/topic_folders/fundraising/index.html

Not sure if this is a question for @Talishask  or @acrall

**Comment by Talishask** [comment]
Thanks Maneesha. I'd recommend that we repurpose the information here. For example: Colloborating with the carpentries on a grant and fundraising are two different things. So initially my thoughts are to 
- put the resources that support people in fundraising for The Carpentries (asking for donations, proposing sponsorship, etc) in one of our general community resource locations, under a fundraising section.
- and put the grant collaboration stuff somewhere else because that is something that is a different activity that requires more connection with our team

**Comment by acrall** [comment]
> put the resources that support people in fundraising for The Carpentries (asking for donations, proposing sponsorship, etc) in one of our general community resource locations, under a fundraising section.

I propose that this go into the [Carpentries Commons repo](https://github.com/carpentries/commons)

> and put the grant collaboration stuff somewhere else because that is something that is a different activity that requires more connection with our team

Would like to keep the "collaborating with The Carpentries on grants" section

**Comment by maneesha** [comment]
See notes from google doc:

- [Fundraising](https://docs.carpentries.org/topic_folders/fundraising/index.html) - what should we do with this? 
- From Kari: Omit the section about the Sponsorship program because it is on the website
- We can publish the guide for collaborating with us on grants on Zenodo, or to the Commons. @OscarSiba  what do you think?
- Donation resources can be moved to the commons. @OscarSiba  what do you think?

**Comment by kariljordan** [comment]
I will take this question to the next CET meeting. cc @OscarSiba @elletjies

**Comment by maneesha** [comment]
In this issue (https://github.com/carpentries/handbook-beta/issues/156) @OscarSiba recommended including the collaborating on grants section and the donation resources section to the front page resources, so that is where I put it.  If you'd like it here as well (or instead of that) please let me know.

**Comment by maneesha** [comment]
I discussed with @OscarSiba today.  We can put the A Guide for Collaborating with The Carpentries on Grants and Donation Request Resources on the new resources page as discussed in #145 and #144.
We will also keep them on the front page.

**Comment by maneesha** [comment]
Addressed with #191
