### ISSUE TITLE
Should Regional Communities pages be in handbook or website? 

### ISSUE THREAD

**Issue by elletjies** [carpentries/handbook-beta#111]
Regional Communities

I am not seeing the regional communities pages (https://docs.carpentries.org/topic_folders/regional_communities/index.html). I use the Africa page to communicate with the community.

**Comment by kariljordan** [comment]
I'm bringing this issue to a CET meeting because I wonder whether this should be on the website.

**Comment by elletjies** [comment]
@maneesha I will move the Africa content to our CodiMD page and will update the link in the subcommunity registry

**Comment by kariljordan** [comment]
The CET met today and discussed the best placement for content related to subcommunities. 

The new website does list our [regional subcommunities](https://beta.carpentries.org/community/get-involved/). Some communities have a link in their heading that either leads to that subcommunity's website or their GitHub repo. Angelique's concern was that the link for Carpentries in Africa leads to the old handbook page of [historical information](https://docs.carpentries.org/topic_folders/regional_communities/african_task_force.html) about Carpentries in Africa. For now, Angelique will transfer the Carpentries in Africa content to a CodiMD page to prevent it from being lost, so the link for Carpentries in Africa will need to be updated so that it goes to the CodiMD page.

@elletjies when you've migrated that content over to the CodiMD page can you submit a PR to update the Carpentries in Africa heading on the [Subcommunity Registry](https://beta.carpentries.org/community/get-connected/#subcommunity-registry) page of the new website?

**Comment by elletjies** [comment]
https://github.com/carpentries/new-website/pull/265

**Comment by maneesha** [comment]
Closing this as the Carpentries in Africa section is now on the website subcommunity listing.
