### ISSUE TITLE
Review Lesson Program Governor Handbook

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#139]
See https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_program_governors

Please consider the following when you review:

- [ ] Is all the content accurate?
- [ ] Do the links all work?
- [ ] Have you noticed any content duplicated in other places? 
- [ ] Any other feedback or suggestions

**Comment by tobyhodges** [comment]
Notes from initial review on 2024-10-22:

- In https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_program_governors#etherpad, adjust wording to say "links to the current etherpad for signing up to upcoming discussion events. "
- In https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_program_governors#topicbox, there is a extraneous . character in "To join one or more Carpentries mailing lists, you will need to [create a login](https://carpentries.topicbox.com/groups/latest). ."
- . missing from the end of the _About this Resource_ part of https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_program_governors#id3

Otherwise all looks good.

**Comment by tobyhodges** [comment]
I will be happy for you to close this after those minor changes are made, @maneesha

**Comment by maneesha** [comment]
Thanks @tobyhodges 
I have fixed the two typos with #184.  I am not changing the text for the etherpad now because I will be updating the link throughout, and it will always point to the current year's etherpad.
