### ISSUE TITLE
Errors in .md file for within text links to Google headings

### ISSUE THREAD

**Issue by acrall** [carpentries/handbook-beta#27]
I was unsure the best way to describe this in the title of this issue, but the Community Discussion Host Handbook included links to headings within the gDoc. When rendering the .md file from the gDoc, these internal headings that allowed you to jump between sections of the handbook produced errors. I removed them for now

**Comment by maneesha** [comment]
@acrall 

This happens because the way that Google Docs generates those anchor links (links to section headings) is different than how they are generated in markdown.

I have edited and merged your PR for the community discussion handbook.  See here: https://carpentries.github.io/handbook-beta/community/discussion_host.html

I have also updated the README of this repo with instructions on how to generate those links.  See: https://github.com/carpentries/handbook-beta#editing-anchor-links

Let me know if this addresses the issue here. If so you can close this issue.  Otherwise, please add any other questions here.

**Comment by acrall** [comment]
@maneesha Your instructions make sense, but I do have a follow-up question. I use the add-on feature to convert a gDoc to Markdown. Can I make any adjustments in that process to automate this or will it need to be done manually?

**Comment by maneesha** [comment]
@acrall I have just updated the README to include a section on managing headers when you use the conversion tool.  Let me know if this makes sense to you.

**Comment by acrall** [comment]
Thanks, @maneesha. That is what I did previously. I was hoping there was a way to make the conversion not include the error messages so you would not have to go in and remove them manually. But, no worries if that is what we need to do. Always looking for shortcuts :-). Closing this issue.
