### ISSUE TITLE
Where should funder acknowledgement be? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#82]
There is a funder acknowledgement at the bottom of the CarpentryCon handbook:

> Funding to develop this handbook was provided by the [Alfred P. Sloan Foundation](https://sloan.org/).

Should this be on the home page instead? Or included in the footer? (see also #73)

**Comment by acrall** [comment]
Perhaps we add it to the "About this Handbook" section instead of having it in is own heading?

**Comment by maneesha** [comment]
Should it be in each handbooks "About this Handbook" section? If it applies to the handbook as a whole, we could consider having a general "About" section.  Also want to hear from @Talishask  about how we need to acknowledge funders.

**Comment by Talishask** [comment]
I'd recommend removing this statement altogether. We have acknowledged our funders in blog posts, our newsletters, annual reports, etc. If we begin leaving notes on everything that a funder supports it could get pretty messy. 

For example what happens if we get funding from another funder to improve this handbook in the future? Do we then ignore what the sloan foundation did or would we then have to say "Funding to develop this handbook was provided by the Alfred P. Sloan Foundation in 20XX. We also received funding from the ORGANISATION NAME FOUNDATION in 20XX to improve this handbook." or "to add _ functionality to this handbook".

**Comment by acrall** [comment]
Each funding organisation provides guidelines on how they want to be acknowledged for products they funded. It seems we need to follow those? Perhaps this is a question for Kari who has more familiarity with those guidelines. Totally understand that it could get messy but think it's important- especially when the organisation funded the development of a specific resource as is the case with the CarpentryCon handbook.

**Comment by Talishask** [comment]
In the grant letters, our funders typically include information about how we can acknowledge their support. That information is typically shared as more like a style guide for when we choose to or want to acknowledge the granting organisation rather than as a requirement. It is possible that I missed something, a guideline or request to be acknowledged in the developed material so I'll ping Kari.

@kariljordan - from our recent grants or at least the one that included the CarpentryCon Handbook, are we required to maintain an acknowledgement regarding the granting organisation on the outcomes of the grant?

Also, do we have any workflows or documentation on maintaining grant acknowledgement post the end of a grant?

**Comment by kariljordan** [comment]
<img width="615" alt="Screen Shot 2023-04-03 at 12 45 55 PM" src="https://user-images.githubusercontent.com/21027863/229574696-63da5819-9efe-4279-9b66-ccd45db9dc4a.png">

I couldn't copy/paste from the PDF, but here's a screenshot from the Sloan (CarpentryCon) grant. 

@Talishask All of the grant award letters are in The Business Team > Grants folder in our shared BT drive. You can look at each award letter and see what the acknowledgment requirements are. We don't have workflows for an acknowledgment after the grant, but if it's a grant that led to a resource it makes sense to include the acknowledgment in the resource.

**Comment by Talishask** [comment]
Thanks Kari! This definitely says that we need to acknowledge the granting organisation on the material.

Alycia, I will add this to our meeting tomorrow to discuss where these acknowledgements should go. I will also check back on the Moore grant and other grant agreements to see if we need to add acknowledgements in more places, like on our website too.
