### ISSUE TITLE
Consistency in "About this handbook" section 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook-beta#95]
Every handbook for community roles has a section "About this handbook" at the very bottom but it is not consistent about what information ins in that section. 

Proposed content that each "About" section should have:
* Description
* Contact info
* Link to glossary
* How to propose changes

It should also be in the same format for each handbook (either a paragraph or a bulleted list).  

Alternatively, we can remove this section from each handbook completely.

**Comment by maneesha** [comment]
@OscarSiba Can you please provide feedback on how to structure the "About this Handbook" section at the bottom of each community role's handbook? Your feedback can also be to say that the section is redundant and should be removed from each community role's handbook :-).

**Comment by OscarSiba** [comment]
I agree that all these "About" sections should also be in the same format for each Handbook, as a paragraph rather than a bulleted list.

- [ ] Also, this section should always be titled "About This Handbook" (there are some that say "About This Section"). 
- [ ] I also think the section should move to the very beginning of each Handbook. 
- [ ] And finally, for all Handbooks the opening/introductory text that currently starts the Handbook should be put under the "Introduction" title which will follow the "About this Handbook" title. 

So, for example, using this page: https://carpentries-beta-handbook-preview.netlify.app/handbooks/lesson_developers

**Lesson Developers Handbook**
**About This Handbook**
This handbook is designed to support members of The Carpentries community who are developing new lessons in The Carpentries Incubator. It is maintained by The Carpentries Curriculum Team. If you believe anything needs to be added or updated here, or if you would like to provide feedback on the content, please email the [Curriculum Team](mailto:curriculum@carpentries.org), or open an issue on the [source repository of this handbook](https://github.com/). If you are unfamiliar with any of the terms used in this handbook, please refer to our [Glossary of terms](https://github.com/carpentries/community-engagement/blob/main/glossary.md).

**Introduction**
Lesson Developers create new lessons using The Carpentries open source lesson infrastructure. This lesson development takes place in The Carpentries Incubator, a space for the community to collaborate on lesson projects.

**Roles and Responsibilities**
Beyond ensuring that the lesson remains compliant with...

**Comment by maneesha** [comment]
Addressed with #177
